version: '3.7'

services:

  cells:
    image: pydio/cells:latest
    restart: unless-stopped
    ports:
      - "8200:8080"
    environment:
      - CELLS_INSTALL_YAML=/pydio/config/install.yml
    volumes: 
      - ./cellsdir:/var/cells
      - ./install-conf.yml:/pydio/config/install.yml:ro

  mysql:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMe!
      MYSQL_DATABASE: cells
      MYSQL_USER: pydio
      MYSQL_PASSWORD: ChangeMe!
    volumes:
      - ./mysqldir:/var/lib/mysql


